name: Run Tests

on: [ pull_request ]

jobs:

  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.20"

      - name: golangci-lint
        continue-on-error: true
        uses: golangci/golangci-lint-action@v5
        with:
          args: --issues-exit-code=0 --timeout=5m

      - name: Run tests
        run: go test -race -coverprofile=coverage.out -covermode=atomic -coverpkg=./... -v ./...

      - name: Upload to codecov
        uses: codecov/codecov-action@v4
        with:
          verbose: true
